package com.sailing.servicemanager.entity;
// Generated 2017-11-8 17:41:59 by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BdspConfEnumType generated by hbm2java
 */
@Entity
@Table(name = "bdsp_conf_enum_type", catalog = "test")
public class BdspConfEnumType implements java.io.Serializable {

    /**
     * serialVersionUID:TODO（用一句话描述这个变量表示什么）
     * @since Ver 1.1
     */
    
    private static final long serialVersionUID = -1906237879470061076L;
    private String id;
    private String parentId;
    private String enumCode;
    private String enumName;
    private String description;
    private String operatePerson;
    private Date operateTime;
    private Character leaf;
    private Character isSystem;
    private Integer seq;

    public BdspConfEnumType() {}

    public BdspConfEnumType(String id, Date operateTime) {
        this.id = id;
        this.operateTime = operateTime;
    }

    public BdspConfEnumType(String id, String parentId, String enumCode, String enumName, String description, String operatePerson, Date operateTime, Character leaf, Character isSystem, Integer seq) {
        this.id = id;
        this.parentId = parentId;
        this.enumCode = enumCode;
        this.enumName = enumName;
        this.description = description;
        this.operatePerson = operatePerson;
        this.operateTime = operateTime;
        this.leaf = leaf;
        this.isSystem = isSystem;
        this.seq = seq;
    }

    @Id

    @Column(name = "ID", unique = true, nullable = false, length = 32)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Column(name = "PARENT_ID", length = 32)
    public String getParentId() {
        return this.parentId;
    }

    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    @Column(name = "ENUM_CODE", length = 100)
    public String getEnumCode() {
        return this.enumCode;
    }

    public void setEnumCode(String enumCode) {
        this.enumCode = enumCode;
    }

    @Column(name = "ENUM_NAME", length = 100)
    public String getEnumName() {
        return this.enumName;
    }

    public void setEnumName(String enumName) {
        this.enumName = enumName;
    }

    @Column(name = "DESCRIPTION", length = 65535)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "OPERATE_PERSON", length = 50)
    public String getOperatePerson() {
        return this.operatePerson;
    }

    public void setOperatePerson(String operatePerson) {
        this.operatePerson = operatePerson;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "OPERATE_TIME", nullable = false, length = 19)
    public Date getOperateTime() {
        return this.operateTime;
    }

    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    @Column(name = "LEAF", length = 1)
    public Character getLeaf() {
        return this.leaf;
    }

    public void setLeaf(Character leaf) {
        this.leaf = leaf;
    }

    @Column(name = "IS_SYSTEM", length = 1)
    public Character getIsSystem() {
        return this.isSystem;
    }

    public void setIsSystem(Character isSystem) {
        this.isSystem = isSystem;
    }

    @Column(name = "SEQ")
    public Integer getSeq() {
        return this.seq;
    }

    public void setSeq(Integer seq) {
        this.seq = seq;
    }

}
