package com.sailing.servicemanager.entity;
// Generated 2017-11-8 17:41:59 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BdspServiceBase generated by hbm2java
 */
@Entity
@Table(name = "bdsp_service_base", catalog = "test")
public class BdspServiceBase implements java.io.Serializable {

    /**
     * serialVersionUID:TODO（用一句话描述这个变量表示什么）
     * @since Ver 1.1
     */
    
    private static final long serialVersionUID = -7782902337990800721L;
    private String serviceId;
    private String serviceCode;
    private String serviceName;
    private String soId;
    private String siCode;
    private String remark;
    private String operatePerson;
    private String operateTime;
    private Character isDesensitization;
    private Character serviceStatus;
    private Character isDelete;
    private Character isEnable;
    private String devLanguage;
    private String bizLine;
    private String topicType;
    private String keyElement;

    public BdspServiceBase() {}

    public BdspServiceBase(String serviceId) {
        this.serviceId = serviceId;
    }

    public BdspServiceBase(String serviceId, String serviceCode, String serviceName, String soId, String siCode, String remark, String operatePerson, String operateTime, Character isDesensitization, Character serviceStatus, Character isDelete, Character isEnable, String devLanguage, String bizLine, String topicType, String keyElement) {
        this.serviceId = serviceId;
        this.serviceCode = serviceCode;
        this.serviceName = serviceName;
        this.soId = soId;
        this.siCode = siCode;
        this.remark = remark;
        this.operatePerson = operatePerson;
        this.operateTime = operateTime;
        this.isDesensitization = isDesensitization;
        this.serviceStatus = serviceStatus;
        this.isDelete = isDelete;
        this.isEnable = isEnable;
        this.devLanguage = devLanguage;
        this.bizLine = bizLine;
        this.topicType = topicType;
        this.keyElement = keyElement;
    }

    @Id

    @Column(name = "SERVICE_ID", unique = true, nullable = false, length = 32)
    public String getServiceId() {
        return this.serviceId;
    }

    public void setServiceId(String serviceId) {
        this.serviceId = serviceId;
    }

    @Column(name = "SERVICE_CODE", length = 100)
    public String getServiceCode() {
        return this.serviceCode;
    }

    public void setServiceCode(String serviceCode) {
        this.serviceCode = serviceCode;
    }

    @Column(name = "SERVICE_NAME", length = 100)
    public String getServiceName() {
        return this.serviceName;
    }

    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }

    @Column(name = "SO_ID", length = 32)
    public String getSoId() {
        return this.soId;
    }

    public void setSoId(String soId) {
        this.soId = soId;
    }

    @Column(name = "SI_CODE", length = 100)
    public String getSiCode() {
        return this.siCode;
    }

    public void setSiCode(String siCode) {
        this.siCode = siCode;
    }

    @Column(name = "REMARK", length = 4000)
    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Column(name = "OPERATE_PERSON", length = 100)
    public String getOperatePerson() {
        return this.operatePerson;
    }

    public void setOperatePerson(String operatePerson) {
        this.operatePerson = operatePerson;
    }

    @Column(name = "OPERATE_TIME", length = 20)
    public String getOperateTime() {
        return this.operateTime;
    }

    public void setOperateTime(String operateTime) {
        this.operateTime = operateTime;
    }

    @Column(name = "IS_DESENSITIZATION", length = 1)
    public Character getIsDesensitization() {
        return this.isDesensitization;
    }

    public void setIsDesensitization(Character isDesensitization) {
        this.isDesensitization = isDesensitization;
    }

    @Column(name = "SERVICE_STATUS", length = 1)
    public Character getServiceStatus() {
        return this.serviceStatus;
    }

    public void setServiceStatus(Character serviceStatus) {
        this.serviceStatus = serviceStatus;
    }

    @Column(name = "IS_DELETE", length = 1)
    public Character getIsDelete() {
        return this.isDelete;
    }

    public void setIsDelete(Character isDelete) {
        this.isDelete = isDelete;
    }

    @Column(name = "IS_ENABLE", length = 1)
    public Character getIsEnable() {
        return this.isEnable;
    }

    public void setIsEnable(Character isEnable) {
        this.isEnable = isEnable;
    }

    @Column(name = "DEV_LANGUAGE", length = 32)
    public String getDevLanguage() {
        return this.devLanguage;
    }

    public void setDevLanguage(String devLanguage) {
        this.devLanguage = devLanguage;
    }

    @Column(name = "BIZ_LINE", length = 32)
    public String getBizLine() {
        return this.bizLine;
    }

    public void setBizLine(String bizLine) {
        this.bizLine = bizLine;
    }

    @Column(name = "TOPIC_TYPE", length = 32)
    public String getTopicType() {
        return this.topicType;
    }

    public void setTopicType(String topicType) {
        this.topicType = topicType;
    }

    @Column(name = "KEY_ELEMENT", length = 32)
    public String getKeyElement() {
        return this.keyElement;
    }

    public void setKeyElement(String keyElement) {
        this.keyElement = keyElement;
    }

}
