package com.sailing.servicemanager.entity;
// Generated 2017-11-8 17:41:59 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BdspServiceEnumRelation generated by hbm2java
 */
@Entity
@Table(name = "bdsp_service_enum_relation", catalog = "test")
public class BdspServiceEnumRelation implements java.io.Serializable {

    /**
     * serialVersionUID:TODO（用一句话描述这个变量表示什么）
     * @since Ver 1.1
     */
    
    private static final long serialVersionUID = -929142538708136095L;
    private String serId;
    private String serviceId;
    private String enumId;
    private String dicId;

    public BdspServiceEnumRelation() {}

    public BdspServiceEnumRelation(String serId) {
        this.serId = serId;
    }

    public BdspServiceEnumRelation(String serId, String serviceId, String enumId, String dicId) {
        this.serId = serId;
        this.serviceId = serviceId;
        this.enumId = enumId;
        this.dicId = dicId;
    }

    @Id

    @Column(name = "SER_ID", unique = true, nullable = false, length = 32)
    public String getSerId() {
        return this.serId;
    }

    public void setSerId(String serId) {
        this.serId = serId;
    }

    @Column(name = "SERVICE_ID", length = 32)
    public String getServiceId() {
        return this.serviceId;
    }

    public void setServiceId(String serviceId) {
        this.serviceId = serviceId;
    }

    @Column(name = "ENUM_ID", length = 32)
    public String getEnumId() {
        return this.enumId;
    }

    public void setEnumId(String enumId) {
        this.enumId = enumId;
    }

    @Column(name = "DIC_ID", length = 32)
    public String getDicId() {
        return this.dicId;
    }

    public void setDicId(String dicId) {
        this.dicId = dicId;
    }

}
