package com.sailing.servicemanager.entity;
// Generated 2017-11-8 17:41:59 by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BdspConfDataDictionary generated by hbm2java
 */
@Entity
@Table(name = "bdsp_conf_data_dictionary", catalog = "test")
public class BdspConfDataDictionary implements java.io.Serializable {

    /**
     * serialVersionUID:TODO（用一句话描述这个变量表示什么）
     * @since Ver 1.1
     */
    
    private static final long serialVersionUID = -6827161534442253169L;
    private String id;
    private String dicCode;
    private String dicName;
    private String description;
    private String operatePerson;
    private Date operateTime;
    private String enumTypeId;
    private Integer dicSequence;

    public BdspConfDataDictionary() {}

    public BdspConfDataDictionary(String id, Date operateTime) {
        this.id = id;
        this.operateTime = operateTime;
    }

    public BdspConfDataDictionary(String id, String dicCode, String dicName, String description, String operatePerson, Date operateTime, String enumTypeId, Integer dicSequence) {
        this.id = id;
        this.dicCode = dicCode;
        this.dicName = dicName;
        this.description = description;
        this.operatePerson = operatePerson;
        this.operateTime = operateTime;
        this.enumTypeId = enumTypeId;
        this.dicSequence = dicSequence;
    }

    @Id

    @Column(name = "ID", unique = true, nullable = false, length = 32)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Column(name = "DIC_CODE", length = 100)
    public String getDicCode() {
        return this.dicCode;
    }

    public void setDicCode(String dicCode) {
        this.dicCode = dicCode;
    }

    @Column(name = "DIC_NAME", length = 100)
    public String getDicName() {
        return this.dicName;
    }

    public void setDicName(String dicName) {
        this.dicName = dicName;
    }

    @Column(name = "DESCRIPTION", length = 65535)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "OPERATE_PERSON", length = 50)
    public String getOperatePerson() {
        return this.operatePerson;
    }

    public void setOperatePerson(String operatePerson) {
        this.operatePerson = operatePerson;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "OPERATE_TIME", nullable = false, length = 19)
    public Date getOperateTime() {
        return this.operateTime;
    }

    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    @Column(name = "ENUM_TYPE_ID", length = 32)
    public String getEnumTypeId() {
        return this.enumTypeId;
    }

    public void setEnumTypeId(String enumTypeId) {
        this.enumTypeId = enumTypeId;
    }

    @Column(name = "DIC_SEQUENCE")
    public Integer getDicSequence() {
        return this.dicSequence;
    }

    public void setDicSequence(Integer dicSequence) {
        this.dicSequence = dicSequence;
    }

}
